from datetime import datetime
# Obtener la fecha actual en formato dd_mm
hoy=datetime.now()
fecha_actual =hoy.strftime('%d.%m.%y')
hoy_carpeta=hoy.strftime('%d_%m')
destino_retirar = r'V:\Excel\\'
# archivo_excel = 'AVAL_TLS_PREGRADO NO VIGENTE  _'+fecha_actual+'.xlsx'
# archivo_excel2 ='AVAL_TLS_PREGRADO VIGENTE  _'+fecha_actual+'.xlsx'

# # archivo_excel = 'AVAL_TLS_PREGRADO NO VIGENTE al  290523.xlsx'
# # archivo_excel2 ='AVAL_TLS_PREGRADO VIGENTE al  290523.xlsx'

# archivos_excel = [
#     archivo_excel,archivo_excel2
# ]


# columnas_deseadas = ['EMPLID', 'TELEFONO3', 'TELEFONO4', 'EMAIL2', 'EMAIL3', 'EMAIL4', 'TIPO ALUMNO','NUM. MASIVA', 'DESCRIPCION']
# nombres_nuevos_eliminar=['TELEFONO3','TELEFONO4','EMAIL2','EMAIL3','EMAIL4','NIVEL ACADEMICO','TIPO ALUMNO','ITEM_NBR','DESCRIPCION ITEM','FECHA DEVENGO']

cabecera = [
    'SOCIEDAD', 'EMPLID', 'CODIGO', 'APELLIDOS', 'NOMBRES', 'DIRECCION', 'DISTRITO', 'TELEFONO1', 'TELEFONO2',
    'TELEFONO3', 'TELEFONO4', 'EMAIL1', 'EMAIL2', 'EMAIL3', 'EMAIL4', 'PROGRAMA', 'CURSO', 'PERIODO',
    'NIVEL ACADEMICO', 'TIPO ALUMNO', 'DESCRIPCION', 'SALDO', 'MONEDA', 'ESTATUS CARRERA', 'MASIVA',
    'NUM. MASIVA', 'ITEM_NBR', 'DESCRIPCION ITEM', 'FECHA DEVENGO', 'FECHA EMISION', 'FECHA VENCIMIENTO',
    'NOTA CRED', 'ID FCRONOGRAMA', 'FECHA FIN PROGRAMA', 'CICLO', 'RAZON SOCIAL', 'RUC', 'TELEFONO EMPRESA',
    'FECHA CORTE', 'DESCR.', 'PALABRA CLAVE2', 'REF.', 'REF. FECHA', 'REF. COMENTARIOS', 'ID ORGANIZACION',
    'CANJE', 'SESION', 'TIPO PROGRAMA ','COD. DUPLI', 'AGENCIAS','SEGMENTACIÓN'
]
cabecera_nueva = ['SOCIEDAD','EMPLID','UNICO','CODIGO', 'APELLIDOS', 'NOMBRES', 'TP_DOC_ID', 'DOC_ID', 'DIRECCION', 'DISTRITO',    'TELEFONO1', 'TELEFONO2', 'TELEFONO3', 'TELEFONO4', 'EMAIL1', 'EMAIL2', 'EMAIL3', 'EMAIL4', 'PROGRAMA', 'CURSO',    'PERIODO', 'NIVEL_ACADEMICO', 'TIPO_ALUMNO', 'DESCRIPCION', 'SALDO', 'MONEDA', 'STATUS_CARRERA', 'MASIVA',    'NUM_MASIVA', 'ITEM_NBR', 'DESCRIPCION_ITEM', 'FECHA_DEVENGO', 'FECHA_EMISION', 'FECHA_VENCIMIENTO', 'NOTA_CRED',    'ID_FCRONOGRAMA', 'FECHA_FIN_PROGRANMA', 'CICLO', 'RAZON_SOCIAL', 'RUC', 'PHONE_EMPRESA', 'FECHA_DE_CORTE',    'DESCR', 'PAL_CLAVE_2', 'REF', 'REF_FECHA', 'REF_COMENTARIOS', 'ID_ORG_EXT', 'CANJE', 'SESION', 'TIPO_PROGRAMA',    'AGENCIA']

# cabecera_nueva = [
#     'SOCIEDAD', 'EMPLID', 'UNICO', 'CODIGO', 'APELLIDOS', 'NOMBRES', 'TP_DOC_ID', 'DOC_ID',
#     'DIRECCION', 'DISTRITO', 'TELEFONO', 'CELULAR', 'EMAIL', 'PROGRAMA', 'CURSO', 'PERIODO',
#     'DESCRIPCION', 'SALDO', 'MONEDA', 'STATUS_CARRERA', 'MASIVA', 'NUM_MASIVA', 'FECHA_EMISION',
#     'FECHA_VENCIMIENTO', 'NOTA_CRED', 'ID_FCRONOGRAMA', 'FECHA_FIN_PROGRANMA', 'CICLO',
#     'RAZON_SOCIAL', 'RUC', 'PHONE_EMPRESA', 'FECHA_DE_CORTE', 'DESCR', 'PAL_CLAVE_2', 'REF',
#     'REF_FECHA', 'REF_COMENTARIOS', 'ID_ORG_EXT', 'CANJE', 'SESION', 'TIPO_PROGRAMA', 'ASESOR'
# ]

